---
policies:
  - type: commit
    spec:
      header:
        length: 120
        imperative: true
        case: lower
        invalidLastCharacters: .
      body:
        required: false
      dco: false
      gpg: false
      spellcheck:
        locale: US
      maximumOfOneCommit: false
      conventional:
        types:
          - refactor
          - perf
          - chore
          - test
          - docs
          - no_type
        scopes:
          - ci
          - deps
          - release
        descriptionLength: 100
